package Poker;

public enum Strategy {
    CALL_MAN,
    EXPECTATION,
    SIMPLE_RANGE,
    SIMPLE_RANGE_EXP,
    SIMPLE_RANGE_EXP_IMP,
    SIMPLE_RANGE_EXP_IMP_IGNPNUM,
    EXACT_RANGE,
    EXACT_RANGE_EXP,
    EXACT_RANGE_EXP_2,
    EXACT_RANGE_EXP_6,
    EXACT_RANGE_EXP_2_FLOP,
    EXACT_RANGE_EXP_6_FLOP,
    EXACT_RANGE_EXP_6_FLOP_EX,
    EXACT_RANGE_EXP_6_FLOP_EX_LIMIT,
    EXACT_RANGE_EXP_12_FLOP_EX_LIMIT,
    EXACT_RANGE_EXP_8_FLOP_EX_LIMIT,
    EXACT_RANGE_EXP_6_24_FLOP_EX_LIMIT,
    EXACT_RANGE_EXP_6_FLOP_EX_LIMIT_LOW,
    EXPECTATION_RAISE_LIMIT_2,
    EXPECTATION_RAISE_LIMIT_24
}
